# Generated by Django 5.1.3 on 2024-11-24 11:00

import restaurants.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_alter_category_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.FileField(upload_to='category_icons/', validators=[restaurants.validators.validate_icon]),
        ),
    ]
